language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - .yarn
notifications:
  email:
    on_failure: always
node_js:
  - 'node'
branches:
  only:
    - "master"
    - /^greenkeeper.*$/

before_install:
  - npm install -g yarn --cache-min 999999999
  - sudo apt-get install -y -q tree

install:
  - yarn

before_deploy:
  - yarn build
  - tree build
deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    branch: master
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: dzv3
  upload-dir: reminders-app
  acl: public_read
  detect_encoding: true
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # Path to a directory containing your built site.
  local_dir: build
  # Set the Cache-Control header.
  cache_control: "max-age=21600"
